logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

spring:
  rabbitmq:
    host: 192.168.100.139  # 主机名
    port: 5672   # 端口
    virtual-host: /  # 虚拟主机
    username: wdd  # 用户名
    password: asd  # 密码
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一条消息